LANGUAGE_CONF = {
    "python": {
        "ecosystem": "PyPI",
        "packages": [
            "django",
            "flask",
            "fastapi",
            "cryptography",
            "requests",
            "pillow",
            "pyyaml",
            "jinja2",
            "sqlalchemy",
            "werkzeug",
            "paramiko",
            "twisted",
            "aiohttp",
            "celery",
            "urllib3",
        ],
        "extensions": [".py"],
        "skip": ["test", "migration", "setup.py"],
    },
    "javascript": {
        "ecosystem": "npm",
        "packages": [
            "lodash",
            "express",
            "axios",
            "jsonwebtoken",
            "mongoose",
            "moment",
            "marked",
            "serialize-javascript",
            "node-fetch",
            "minimist",
            "tar",
            "semver",
            "ws",
            "ejs",
            "handlebars",
        ],
        "extensions": [".js", ".ts", ".mjs"],
        "skip": ["test", "spec", "__tests__", ".min.js"],
    },
    "java": {
        "ecosystem": "Maven",
        "packages": [
            "org.apache.commons:commons-text",
            "org.springframework:spring-core",
            "com.fasterxml.jackson.core:jackson-databind",
            "org.apache.struts:struts2-core",
            "org.apache.logging.log4j:log4j-core",
        ],
        "extensions": [".java"],
        "skip": ["test.java", "test/", "spec/"],
    },
    "ruby": {
        "ecosystem": "RubyGems",
        "packages": [
            "rails",
            "devise",
            "nokogiri",
            "rack",
            "actionpack",
            "activesupport",
            "carrierwave",
        ],
        "extensions": [".rb"],
        "skip": ["spec/", "_test.rb", "test/"],
    },
    "c++": {
        "ecosystem": "OSS-Fuzz",
        "packages": [
            "curl",
            "mbedtls",
            "libpng",
            "libtiff",
            "ffmpeg",
            "imagemagick",
            "sqlite3",
            "zlib",
            "systemd",
            "freetype2",
        ],
        "extensions": [".c", ".cpp", ".cc", ".cxx", ".h", ".hpp"],
        "skip": ["test", "fuzz", "mock", "third_party", "cmake"],
    },
}
